### ISSUE TITLE
make it deployable on heroku

### ISSUE THREAD

**Issue by branchmaster** [FlerioEU/erc721-token-color#1]
Hi Flerio ,
please make deploy to heroku button for easy deploy & make this project permanent usage free of personal system usage or any paid invoice server must be bill.
i think project below can help you :
https://github.com/branchmaster/Charity-Blockchain
waiting for your response
finest regards

**Comment by FlerioEU** [comment]
Hey Branchmaster,

thanks for your Feedback!

I'm unfamiliar with Heroku. What would be the benefit adding it? Are you not able to run this project locally?

Best regards

**Comment by FlerioEU** [comment]
Since there is no further Feedback i will close this Issue. If there are any other suggestions you would like to see please open a new issue
